---
- name: Install Apache2
  ansible.builtin.apt:
    name: apache2
    update_cache: yes
    state: latest

- name: Create document root
  ansible.builtin.file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ app_user }}"
    mode: '0755'

- name: Copy index test page
  ansible.builtin.template:
    src: "templates/index.html.j2"
    dest: "/var/www/{{ http_host }}/index.html"

- name: Set up Apache virtuahHost
  ansible.builtin.template:
    src: "templates/apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"

- name: Enable new site
  ansible.builtin.command: /usr/sbin/a2ensite {{ http_conf }}
  notify: Reload Apache

- name: Disable default Apache site
  shell: /usr/sbin/a2dissite 000-default.conf
  when: disable_default
  notify: Reload Apache

# SSL
- name: Create SSL Directoru
  ansible.builtin.file:
    path: "/var/www/{{ http_host }}/ssl"
    state: directory
    mode: '0755'
  when: http_ssl|bool 

- name: Install OpenSSL
  ansible.builtin.apt:
    state: present
    update_cache: yes
    name:
      - openssl
  when: http_ssl|bool 

- name: Generate an OpenSSH keypair with the default values (ed25519)
  community.crypto.openssl_privatekey:
    type: Ed25519
    path: "/var/www/{{ http_host }}/ssl/server.key"
  when: http_ssl|bool 

- name: Create self-signed certificate
  community.crypto.x509_certificate:
    path: "/var/www/{{ http_host }}/ssl/server.crt"
    privatekey_path: "/var/www/{{ http_host }}/ssl/server.key"
    provider: selfsigned
  when: http_ssl|bool 