---
- name: Installation des outils additionel
  ansible.builtin.apt:
    state: present
    update_cache: yes
    name:
      - sysstat
      - software-properties-common
      - apt-transport-https
      - figlet  