---
- name: Create .zshrc for users with autoload ssh
  ansible.builtin.template:
    src: .zshrc.j2
    dest: /home/{{ item.name }}/.zshrc
    mode: '0644'
  when: item.servers | intersect(group_names) and ((item.ssh_statue is defined) and (item.ssh_statue is true))
  with_items: "{{ users }}"

- name: Create .bahsrc for users with autoload ssh (optional)
  ansible.builtin.template:
    src: .bashrc.j2
    dest: /home/{{ item.name }}/.bashrc
    mode: '0644'
  when: item.servers | intersect(group_names) and ((item.ssh_statue is defined) and (item.ssh_statue is true))
  with_items: "{{ users }}"