---
- name: Create User Group
  ansible.builtin.group:
    name: "{{ item.primary_group }}"
    state: present
  with_items: "{{ users }}"

- name: Create User
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.group }}, wheel"
    state: present
    shell: "{{ default_shell }}"
  with_items: "{{ users }}"

- name: Load User SSH
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh.work_key }}"
  with_items: "{{ users }}"

- name: Create ssh config
  ansible.builtin.template:
    src: config.j2
    dest: /home/{{ item.name }}/.ssh/config
    mode: '0644'
  with_items: "{{ users }}"