---
- name: Set root shell
  ansible.builtin.user:
    name: root
    shell: "/bin/zsh"

- name: Create Group
  ansible.builtin.group:
    name: "{{ user.group }}"
    gid: 1000
    state: present

- name: Create User
  ansible.builtin.user:
    name: "{{ user.name }}"
    uid: 1000
    group: "{{ user.group }}, wheel"
    state: present
    shell: "/bin/{{ user.shell }}"
    comment: "{{ user.comment }}"

- name: Load User SSH
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    key: "{{ user.ssh_work_key }}"

- name: Create ssh config
  ansible.builtin.template:
    src: config.j2
    dest: /home/{{ user.name }}/.ssh/config
    mode: '0644'