default_shell: /bin/zsh
location: "{{ 'Shrine' if inventory_hostname == localhost else 'Remote' }}"

users:
  - name: domino659
    pswd: pingu
    comment: "Martin SION"
    primary_group: domino659
    # pas implementer
    servers:
      - home
      - vm

    # Give user secondary group:
    # wheel: Access to sudo
    # wheel_no_pswd: Access to sudo without password
    groups:
      - wheel_no_pswd
      
    # Set ssh keys
    ssh_statue: true
    ssh:
        # Work Key
      - name: msion_axians
        key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGRcoQQLa0PB7j9kjF2SJ8xpfW97nktu69AEdcejhDry domino659 15/02/2022
        # Private Key
      - name: private_domino659
        key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPV2jqEqFgS3qjntWqseCQ/1nqywd/ueT8YsrztsUYY6 domino659 02/03/2022
    
    # Set git config
    git:
      statue: true
      name: domino659
      email: martin@sionfamily.com
    
    # Set symbolic link to a drive
    drive:
      statue: true
      location: g

# - name: nolex
#   group: nolex
#   sudo_password: root
#   comment: Wiss
#   # Choice custom zsh or native bash
#   shell: zsh
#   ssh_work_name: id_ed25519
#   ssh_work_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINc6myG0zQ7C6+b/ArX0LLZ8vQBhXPWL1e8QxShDMZHZ elaouni.wissam@gmail.com