---
- name: Enable ssl on apache2
  community.general.apache2_module:
    state: present
    name: ssl
  # when: http_ssl|bool

- name: Install OpenSSL and python3-cryptography (required)
  ansible.builtin.apt:
    state: present
    update_cache: yes
    name:
      - openssl
      - python3-cryptography
  # when: http_ssl|bool

- name: Create SSL Directory Key
  ansible.builtin.file:
    path: "/etc/ssl/private/{{ host_file }}"
    state: directory
    mode: '0755'
  # when: http_ssl|bool

- name: Create SSL Directory Certs
  ansible.builtin.file:
    path: "/etc/ssl/certs/{{ host_file }}"
    state: directory
    mode: '0755'
  # when: http_ssl|bool

- name: Generate an OpenSSH keypair with the default values (ed25519)
  community.crypto.openssl_privatekey:
    type: Ed25519
    path: "/etc/ssl/private/{{ host_file }}/server.key"
  # when: http_ssl|bool

- name: Create a self-signed certificate
  community.crypto.x509_certificate:
    path: "/etc/ssl/certs/{{ host_file }}/server.crt"
    privatekey_path: "/etc/ssl/private/{{ host_file }}/server.key"
    provider: selfsigned
    entrust_requester_name: "{{ ssl.name }}"
    entrust_requester_email: "{{ ssl.email }}"
  # when: http_ssl|bool
