---
- hosts: vm
  name: Setup Workspace
  remote_user: root
  serial: 1
  become: true

  vars_files:
   - config/var.yml

  tasks:
  - name: Installation des outils de base
    ansible.builtin.apt:
      state: present
      update_cache: yes
      name:
        - zsh
        - zsh-syntax-highlighting
        - zsh-autosuggestions
        - ksh
        - vim
        - htop
        - iftop
        - tree
        - net-tools
        - screen
        - python3-pexpect
        - python3-cryptography
        - sudo
        - ccze
        - gnupg2
        - wget
        - curl
        - grc
        - molly-guard

  # Local
  roles:
    - { role: user/local/additional_package }
    # User
    - { role: user/local/config_zsh, tags: ['user',] }
    - { role: user/local/my_user, tags: ['user'] }

  # Remote
  # roles:
  #   # User
  #   - { role: user/remote/zconfig_zsh, tags: ['user',] }
  #   - { role: user/remote/my_user, tags: ['user'] }