---
- hosts: vm
  name: Setup Workspace
  remote_user: root
  serial: 1
  become: true

  vars_files:
   - config/var.yml

  tasks:
  - name: Installation des outils de base
    ansible.builtin.apt:
      state: present
      update_cache: yes
      name:
        - zsh
        - zsh-syntax-highlighting
        - zsh-autosuggestions
        - sudo

  roles:
    - { role: user/additional_package, tags: ['additional'] }
    # User
    - { role: user/config_zsh, tags: ['user'] }
    - { role: user/my_user, tags: ['user'] }