---
- hosts: all
  name: Setup Workspace Installation
  remote_user: root
  serial: 1
  become: true

  vars_files:
   - config/var.yml
   - config/users.yml

  # If localhost Shine else Remote
  var:
    location: Shrine

  tasks:
  - name: Installation package de base
    ansible.builtin.apt:
      state: present
      update_cache: yes
      name:
        - zsh
        - zsh-syntax-highlighting
        - zsh-autosuggestions
        - sudo
        - grc
        - ccze

  roles:
    - { role: user/additional_packages, when: ansible_hostname == localhost }

- hosts: all
  name: Setup Workspace Parametrage
  remote_user: root
  serial: 1
  become: true

  vars_files:
   - config/var.yml

  roles:
    - { role: user/sudo }
    - { role: user/zsh }
    # If local
    - {role: user/ssh, when: add_ssh }
    - { role: user/my_user }
      # If local
    - { role: user/link, when: user.drive|length > 0 }
      # If local
    - {role: user/git, when: add_git }