---
- hosts: vm
  name: Setup Workspace Installation
  remote_user: root
  serial: 1
  become: true

  vars_files:
   - config/var.yml

  tasks:
  - name: Installation des outils de base
    ansible.builtin.apt:
      state: present
      update_cache: yes
      name:
        - zsh
        - zsh-syntax-highlighting
        - zsh-autosuggestions
        - sudo
        - grc
        - ccze

  roles:
    - { role: user/additional_package, tags: ['additional'] }

- hosts: vm
  name: Setup Workspace Parametrage
  remote_user: root
  serial: 1
  become: true

  vars_files:
   - config/var.yml

  roles:
    - { role: user/settings_sudo }
    - { role: user/config_zsh }
    - { role: user/my_user }