---
- hosts: all
  name: Setup Workspace
  remote_user: root
  serial: 1
  become: true

  vars_files:
    - config/vault.yml
    - config/var.yml
    - config/users.yml

  tasks:
  - name: Installation package de base
    ansible.builtin.apt:
      state: present
      update_cache: yes
      name:
        - zsh
        - zsh-syntax-highlighting
        - zsh-autosuggestions
        - sudo
        - grc
        - ccze

  roles:
    - { role: user/additional_packages, when: inventory_hostname == localhost }

- hosts: all
  name: Setup Workspace Parametrage
  remote_user: root
  serial: 1
  become: true

  vars_files:
    - config/vault.yml
    - config/var.yml
    - config/users.yml

  roles:
    - { role: user/sudo }
    - { role: user/zsh }
    - { role: user/my_user }
    - { role: user/ssh, when: (inventory_hostname == localhost) }
    - { role: user/link, when: (inventory_hostname == localhost) }
    - { role: user/git, when: (inventory_hostname == localhost) }