---
- hosts: vm
  name: Setup Workspace
  remote_user: root
  serial: 1
  become: true

  vars_files:
   - config/var.yml

  roles:
    - { role: web/installation_apache2 }

  # Créer vhost apache2 qui repondra a ganymede.gwath-land.fr et afficher une page specifique
  # apache en ssl 
  # certificat autosigné ansible
  # ssl 443
  # cle certificat privé certificat publique