---
- hosts: vm
  name: Setup application Web
  # remote_user: root
  serial: 1
  become: true

  vars_files:
    - config/vault.yml
    - config/var.yml
    - config/users.yml

  roles:
    - { role: web/application_web }