---
- hosts: vm
  name: Setup Workspace
  remote_user: root
  serial: 1
  become: true

  vars_files:
   - config/var.yml

  roles:
    - { role: web/installation_apache2 }
    - role: web/ssl
      when: http_ssl|bool
    - { role: web/vhost }