---
- name: Create symbolic link between WLS and Drive
  ansible.builtin.file:
    src: "/mnt/{{ item.drive.location }}/Mon\ Drive/Code"
    dest: "/home/{{ item.name }}/Drive"
    owner: domino659
    group: domino659
    state: link
  when: item.servers | intersect(group_names) and ((item.drive.statue is defined) and (item.drive.statue is true))
  with_items: "{{ users }}"