---
- name: Create symbolic link between WLS and Drive
  ansible.builtin.file:
    src: "/mnt/{{ item.drive }}/Mon\ Drive/Code"
    dest: "/home/{{ item.name }}/Drive"
    owner: domino659
    group: domino659
    state: link
  when: ansible_hostname == localhost
  with_items: "{{ users }}"