---
- name: Installation de git
  ansible.builtin.apt:
    state: present
    update_cache: yes
    name:
      - git

- name: Create .gitconfig for user
  ansible.builtin.template:
    src: .gitconfig.j2
    dest: /home/{{ item.name }}/.gitconfig
    mode: '0644'
  when: item.git.statue
  with_items: "{{ users }}"