---
- name: Installation de git
  ansible.builtin.apt:
    state: present
    update_cache: yes
    name:
      - git
  when: item.servers | intersect(group_names) and ((item.git.statue is defined) and (item.git.statue is true))
  with_items: "{{ users }}"

- name: Create .gitconfig for user
  ansible.builtin.template:
    src: .gitconfig.j2
    dest: /home/{{ item.name }}/.gitconfig
    mode: '0644'
  when: item.servers | intersect(group_names) and ((item.git.statue is defined) and (item.git.statue is true))
  with_items: "{{ users }}"